title: Blake's GitHub Page
author: Blake McClung
email: blaker.mcclung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Blake McClung and I am a Master of Business Analytics student at the University of Iowa. 
  I will be sharing my projects and experiences in data analytics on this page. Please 

# social links
linked_username: www.linkedin.com/in/blake-mcclung
github_username:  bmcclung

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
